---
name: test-network-n2m
version: 1.0.0
client:
  organization: n2m
  connection:
    timeout:
      peer:
        endorser: "300"
organizations:
  n2mMSP:
    mspid: n2mMSP
    peers:
      - peer0.n2m.cityhub.org
    certificateAuthorities:
      - ca.n2m.cityhub.org
peers:
  peer0.n2m.cityhub.org:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
          MIICVDCCAfqgAwIBAgIRAO0cBNNqsVm2rs1L7UaNjUswCgYIKoZIzj0EAwIwdDEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGDAWBgNVBAoTD24ybS5jaXR5aHViLm9yZzEeMBwGA1UEAxMVdGxz
          Y2EubjJtLmNpdHlodWIub3JnMB4XDTIyMTExNjAxNTMwMFoXDTMyMTExMzAxNTMw
          MFowdDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcT
          DVNhbiBGcmFuY2lzY28xGDAWBgNVBAoTD24ybS5jaXR5aHViLm9yZzEeMBwGA1UE
          AxMVdGxzY2EubjJtLmNpdHlodWIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
          QgAEBeVSEs5bUOkTvbeMSnR+A/FljrpkRB5MZrnHNeuI+AOtxVwxoicnygepeN1a
          MhcjnnxXTHERoUtlq3AvSrwXf6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQW
          MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQi
          BCCEs5V4XGt5cdtl9XuJXnA5GNucrxq9wIKV9ZLF4zNWJDAKBggqhkjOPQQDAgNI
          ADBFAiEAt3KfYk6yYkWXnA6ia3S0yG7IOBMUvIZy2qJO77beKfQCIH6f3K0C91AU
          8vabp5zHK7RMDXQ8YovP+OBfVPAziwJZ
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.n2m.cityhub.org
      hostnameOverride: peer0.n2m.cityhub.org
certificateAuthorities:
  ca.n2m.cityhub.org:
    url: https://localhost:7054
    caName: ca.n2m.cityhub.org
    tlsCACerts:
      pem:
        - |
          -----BEGIN CERTIFICATE-----
          MIICTTCCAfOgAwIBAgIQJS7YsgQOPTpFw0b12Vf38jAKBggqhkjOPQQDAjBxMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEYMBYGA1UEChMPbjJtLmNpdHlodWIub3JnMRswGQYDVQQDExJjYS5u
          Mm0uY2l0eWh1Yi5vcmcwHhcNMjIxMTE2MDE1MzAwWhcNMzIxMTEzMDE1MzAwWjBx
          MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2Fu
          IEZyYW5jaXNjbzEYMBYGA1UEChMPbjJtLmNpdHlodWIub3JnMRswGQYDVQQDExJj
          YS5uMm0uY2l0eWh1Yi5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASiW90O
          ezKoyMvK5o6dQOaYBvF82pjJXg34pOlAgmp+Fj5L3X+qEUbfe64cNLpXQyuc1wda
          sxL+UuE7ywAINZ3zo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYB
          BQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIH53lhyp
          Gk+IJE0hbS4FYuf1YCbpuxxyCwnalJ8vZfBaMAoGCCqGSM49BAMCA0gAMEUCIQCs
          r2wpgZTtZ8m0bLT/eJXO2S9RyZFSfVP+shBiv9XwgQIgcsRnYb9yKR/gYy/K5A9M
          fnEgFQyuiEhvyB81KYps4kQ=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
